### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by limelect** [davidcesarino/Decode#1]
RecorU and about DFM missing

**Comment by limelect** [comment]
RecordeU ?? but still a mess

**Comment by davidcesarino** [comment]
Fixed.

I clarified the purpose of these projects in the new README. In short, these were one of my first programming projects ever (I keep them here as a personal memory vault), and I know the code is utter spaguetti crap. I was a kid and started learning (some) programming with them.

They are confirmed now to open with Delphi 2007, compile and run without issues.
